version: "3.9"

services:
  db:
    image: postgres:16
    container_name: journalcommerce-db
    restart: always
    environment:
      POSTGRES_USER: jc_user
      POSTGRES_PASSWORD: jc_password
      POSTGRES_DB: journalcommerce
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: